title: Levin Eric Zimmermann
author: Levin Eric Zimmermann
tagline: Page of composer and software developer Levin Zimmermann
url: "https://levinericzimmermann.eu"
baseurl: ""
soundcloud: levinericzimmermann
github: levinericzimmermann
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
description: Levin Eric Zimmermann is a German composer, software developer and musician. He works in the fields of Just Intonation, computer-assisted composition and sound art.
social:
  name: Levin Zimmermann
  links:
    - https://levinericzimmermann.bandcamp.com/
    - https://soundcloud.com/levinericzimmermann
    - https://github.com/levinericzimmermann
    - https://github.com/mutwo-org
favicon_location: assets/favicon/favicon.ico
favicon: yes


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_list:
  - name: "bandcamp"
    url: "https://levinericzimmermann.bandcamp.com/"
    img_url: "https://www.seekpng.com/png/detail/113-1133459_open-bandcamp-logo-white-png.png"
  - name: "soundcloud"
    url: "https://soundcloud.com/levinericzimmermann"
    img_url: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmaxcdn.icons8.com%2FShare%2Ficon%2FLogos%2Fsoundcloud1600.png&f=1&nofb=1"
  - name: "github"
    url: "https://github.com/levinericzimmermann"
    img_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/about"
 - name: "works"
   link: "/works"
 - name: "dates"
   link: "/dates"
 - name: "etc"
   link: "/etc"
 - name: "contact"
   link: "/contact"
