#!/usr/bin/env bash
# Please see https://matthewrhone.dev/jekyll-in-nixos
nix-shell -p bundler -p bundix --run 'bundler update; bundler lock; bundler package --no-install --path vendor; bundix; rm -rf vendor'
